pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Koushik0802/MyRepo.git', branch: 'main'
            }
        }
		
        
        stage('Execute') {
            steps {
              javac simple-java/Javafile.java
              java Javafile.java
            }
        }
    }
}
